// 开局一课2026 院校报名数据 - 自动生成于 2026-04-20
// 数据源: 企微文档报名底表反查 + 目标院校标签表
// 总报名: 1,990人 | 目标院校: 951人(47.8%) | 非目标院校: 1,039人(52.2%)
const SCHOOLS = [
  // === C9 (9所) ===
  {name:'浙江大学',tag:'C9',uhr:'junoyjchen',count:51,s:19,c:18,a:4,o:10},
  {name:'复旦大学',tag:'C9',uhr:'junoyjchen',count:27,s:10,c:6,a:1,o:10},
  {name:'北京大学',tag:'C9',uhr:'ivanboli',count:26,s:14,c:2,a:0,o:10},
  {name:'清华大学',tag:'C9',uhr:'ericdhdeng',count:19,s:8,c:5,a:3,o:3},
  {name:'南京大学',tag:'C9',uhr:'chenninggu',count:15,s:5,c:2,a:2,o:6},
  {name:'上海交通大学',tag:'C9',uhr:'junoyjchen',count:14,s:9,c:2,a:0,o:3},
  {name:'哈尔滨工业大学',tag:'C9',uhr:'ivanboli',count:12,s:6,c:0,a:2,o:4},
  {name:'西安交通大学',tag:'C9',uhr:'siennaliu',count:11,s:6,c:4,a:0,o:1},
  {name:'中国科学技术大学',tag:'C9',uhr:'chenninggu',count:5,s:3,c:1,a:0,o:1},
  // === T28 (16所) ===
  {name:'电子科技大学',tag:'T28',uhr:'siennaliu',count:31,s:8,c:22,a:0,o:1},
  {name:'中山大学',tag:'T28',uhr:'elenapeng',count:26,s:10,c:8,a:0,o:8},
  {name:'华南理工大学',tag:'T28',uhr:'elenapeng',count:23,s:10,c:7,a:0,o:6},
  {name:'武汉大学',tag:'T28',uhr:'yichenjiang',count:16,s:7,c:5,a:0,o:4},
  {name:'四川大学',tag:'T28',uhr:'siennaliu',count:15,s:7,c:4,a:1,o:3},
  {name:'华中科技大学',tag:'T28',uhr:'yichenjiang',count:14,s:3,c:5,a:0,o:6},
  {name:'西安电子科技大学',tag:'T28',uhr:'siennaliu',count:14,s:4,c:7,a:1,o:2},
  {name:'东南大学',tag:'T28',uhr:'chenninggu',count:11,s:6,c:2,a:1,o:2},
  {name:'北京邮电大学',tag:'T28',uhr:'ivanboli',count:10,s:5,c:5,a:0,o:0},
  {name:'中国人民大学',tag:'T28',uhr:'ericdhdeng',count:8,s:6,c:0,a:0,o:2},
  {name:'北京航空航天大学',tag:'T28',uhr:'ericdhdeng',count:7,s:1,c:5,a:1,o:0},
  {name:'中国科学院大学',tag:'T28',uhr:'nikkyxu',count:6,s:0,c:5,a:0,o:1},
  {name:'哈尔滨工业大学（深圳）',tag:'T28',uhr:'elenapeng',count:3,s:1,c:2,a:0,o:0},
  {name:'西北工业大学',tag:'T28',uhr:'siennaliu',count:3,s:0,c:1,a:0,o:2},
  {name:'清华大学（深圳）',tag:'T28',uhr:'elenapeng',count:0,s:0,c:0,a:0,o:0},
  {name:'北京大学（深圳）',tag:'T28',uhr:'elenapeng',count:0,s:0,c:0,a:0,o:0},
  // === T60 (30所) ===
  {name:'深圳大学',tag:'T60',uhr:'elenapeng',count:42,s:18,c:12,a:5,o:7},
  {name:'香港中文大学（深圳）',tag:'T60',uhr:'elenapeng',count:29,s:9,c:10,a:0,o:10},
  {name:'华东师范大学',tag:'T60',uhr:'chenninggu',count:19,s:5,c:5,a:2,o:7},
  {name:'广东工业大学',tag:'T60',uhr:'estelleyin',count:17,s:8,c:5,a:2,o:2},
  {name:'暨南大学',tag:'T60',uhr:'estelleyin',count:17,s:7,c:1,a:0,o:9},
  {name:'同济大学',tag:'T60',uhr:'junoyjchen',count:13,s:5,c:3,a:1,o:4},
  {name:'大连理工大学',tag:'T60',uhr:'ivanboli',count:12,s:4,c:5,a:0,o:3},
  {name:'华南师范大学',tag:'T60',uhr:'estelleyin',count:10,s:2,c:4,a:0,o:4},
  {name:'武汉理工大学',tag:'T60',uhr:'adinaluo',count:10,s:0,c:1,a:5,o:4},
  {name:'南京邮电大学',tag:'T60',uhr:'chenninggu',count:9,s:2,c:4,a:1,o:2},
  {name:'湖南大学',tag:'T60',uhr:'adinaluo',count:9,s:3,c:4,a:0,o:2},
  {name:'厦门大学',tag:'T60',uhr:'estelleyin',count:9,s:4,c:0,a:0,o:5},
  {name:'重庆邮电大学',tag:'T60',uhr:'siennaliu',count:8,s:1,c:5,a:1,o:1},
  {name:'东北大学',tag:'T60',uhr:'ivanboli',count:8,s:3,c:3,a:1,o:1},
  {name:'南开大学',tag:'T60',uhr:'ericdhdeng',count:7,s:3,c:1,a:0,o:3},
  {name:'天津大学',tag:'T60',uhr:'ericdhdeng',count:7,s:2,c:4,a:0,o:1},
  {name:'杭州电子科技大学',tag:'T60',uhr:'junoyjchen',count:6,s:3,c:2,a:1,o:0},
  {name:'中南大学',tag:'T60',uhr:'adinaluo',count:6,s:2,c:3,a:0,o:1},
  {name:'山东大学',tag:'T60',uhr:'ericdhdeng',count:6,s:3,c:2,a:0,o:1},
  {name:'北京交通大学',tag:'T60',uhr:'jiawenzhou',count:5,s:2,c:1,a:0,o:2},
  {name:'西南交通大学',tag:'T60',uhr:'siennaliu',count:4,s:2,c:2,a:0,o:0},
  {name:'北京科技大学',tag:'T60',uhr:'jiawenzhou',count:4,s:1,c:2,a:0,o:1},
  {name:'哈尔滨工程大学',tag:'T60',uhr:'ivanboli',count:4,s:1,c:2,a:0,o:1},
  {name:'南方科技大学',tag:'T60',uhr:'elenapeng',count:4,s:1,c:2,a:0,o:1},
  {name:'中国地质大学（武汉）',tag:'T60',uhr:'yichenjiang',count:4,s:0,c:0,a:0,o:4},
  {name:'华中师范大学',tag:'T60',uhr:'adinaluo',count:3,s:1,c:1,a:0,o:1},
  {name:'重庆大学',tag:'T60',uhr:'siennaliu',count:3,s:2,c:0,a:0,o:1},
  {name:'西安邮电大学',tag:'T60',uhr:'siennaliu',count:3,s:0,c:2,a:1,o:0},
  {name:'北京理工大学',tag:'T60',uhr:'ivanboli',count:1,s:1,c:0,a:0,o:0},
  {name:'国防科技大学',tag:'T60',uhr:'adinaluo',count:0,s:0,c:0,a:0,o:0},
  // === 美术院校 (15所) ===
  {name:'中国传媒大学',tag:'美术院校',uhr:'ericdhdeng',count:32,s:12,c:8,a:1,o:11},
  {name:'中国美术学院',tag:'美术院校',uhr:'nikkyxu',count:15,s:3,c:1,a:11,o:0},
  {name:'中央美术学院',tag:'美术院校',uhr:'nikkyxu',count:15,s:3,c:0,a:12,o:0},
  {name:'广州美术学院',tag:'美术院校',uhr:'siennaliu',count:8,s:3,c:0,a:4,o:1},
  {name:'吉林动画学院',tag:'美术院校',uhr:'nikkyxu',count:8,s:1,c:0,a:7,o:0},
  {name:'江南大学',tag:'美术院校',uhr:'chenninggu',count:7,s:1,c:3,a:3,o:0},
  {name:'北京电影学院',tag:'美术院校',uhr:'ivanboli',count:6,s:2,c:0,a:3,o:1},
  {name:'四川美术学院',tag:'美术院校',uhr:'siennaliu',count:4,s:0,c:0,a:2,o:2},
  {name:'鲁迅美术学院',tag:'美术院校',uhr:'ivanboli',count:3,s:1,c:0,a:2,o:0},
  {name:'四川音乐学院',tag:'美术院校',uhr:'siennaliu',count:2,s:1,c:0,a:0,o:1},
  {name:'西安美术学院',tag:'美术院校',uhr:'siennaliu',count:2,s:1,c:0,a:1,o:0},
  {name:'湖北美术学院',tag:'美术院校',uhr:'yichenjiang',count:2,s:0,c:0,a:2,o:0},
  {name:'天津美术学院',tag:'美术院校',uhr:'ivanboli',count:2,s:0,c:0,a:0,o:2},
  {name:'清华大学美术学院',tag:'美术院校',uhr:'ericdhdeng',count:0,s:0,c:0,a:0,o:0},
  {name:'南京艺术学院',tag:'美术院校',uhr:'chenninggu',count:0,s:0,c:0,a:0,o:0},
  // === 垂类 (14所) ===
  {name:'北京师范大学',tag:'垂类',uhr:'ericdhdeng',count:9,s:4,c:2,a:0,o:3},
  {name:'上海财经大学',tag:'垂类',uhr:'chenninggu',count:8,s:3,c:1,a:0,o:4},
  {name:'西南财经大学',tag:'垂类',uhr:'siennaliu',count:4,s:1,c:0,a:0,o:3},
  {name:'上海戏剧学院',tag:'垂类',uhr:'',count:3,s:2,c:0,a:1,o:0},
  {name:'西北大学',tag:'垂类',uhr:'siennaliu',count:3,s:1,c:1,a:0,o:1},
  {name:'对外经济贸易大学',tag:'垂类',uhr:'ericdhdeng',count:2,s:1,c:0,a:0,o:1},
  {name:'中央财经大学',tag:'垂类',uhr:'ericdhdeng',count:2,s:1,c:0,a:0,o:1},
  {name:'中国政法大学',tag:'垂类',uhr:'ericdhdeng',count:2,s:0,c:0,a:0,o:2},
  {name:'陕西师范大学',tag:'垂类',uhr:'siennaliu',count:1,s:1,c:0,a:0,o:0},
  {name:'中央戏剧学院',tag:'垂类',uhr:'',count:1,s:1,c:0,a:0,o:0},
  {name:'江西财经大学',tag:'垂类',uhr:'Nikkyxu',count:1,s:0,c:0,a:0,o:1},
  {name:'四川大学锦江学院',tag:'垂类',uhr:'Nikkyxu',count:0,s:0,c:0,a:0,o:0},
  {name:'电子科大成都学院',tag:'垂类',uhr:'Nikkyxu',count:0,s:0,c:0,a:0,o:0},
  {name:'西安建筑工业大学',tag:'垂类',uhr:'',count:0,s:0,c:0,a:0,o:0},
  // === 长尾 (4所) ===
  {name:'吉林大学',tag:'长尾',uhr:'ivanboli',count:6,s:2,c:1,a:0,o:3},
  {name:'上海外国语大学',tag:'长尾',uhr:'chenninggu',count:3,s:0,c:0,a:0,o:3},
  {name:'北京师范大学（珠海）',tag:'长尾',uhr:'elenapeng',count:0,s:0,c:0,a:0,o:0},
  {name:'电子科技大学（深圳）',tag:'长尾',uhr:'elenapeng',count:0,s:0,c:0,a:0,o:0},
  // === 海外 (55所) ===
  {name:'香港大学',tag:'海外',uhr:'denazhu',count:26,s:9,c:5,a:0,o:12},
  {name:'香港城市大学',tag:'海外',uhr:'denazhu',count:17,s:6,c:1,a:0,o:10},
  {name:'香港理工大学',tag:'海外',uhr:'denazhu',count:13,s:4,c:4,a:2,o:3},
  {name:'香港中文大学',tag:'海外',uhr:'denazhu',count:11,s:6,c:1,a:0,o:4},
  {name:'香港科技大学',tag:'海外',uhr:'denazhu',count:11,s:3,c:5,a:0,o:3},
  {name:'悉尼大学',tag:'海外',uhr:'nikkyxu',count:10,s:4,c:3,a:0,o:3},
  {name:'新南威尔士大学',tag:'海外',uhr:'nikkyxu',count:8,s:4,c:3,a:1,o:0},
  {name:'新加坡国立大学',tag:'海外',uhr:'nikkyxu',count:7,s:3,c:2,a:0,o:2},
  {name:'香港浸会大学',tag:'海外',uhr:'denazhu',count:5,s:4,c:0,a:0,o:1},
  {name:'南洋理工大学',tag:'海外',uhr:'nikkyxu',count:5,s:0,c:1,a:1,o:3},
  {name:'加州大学伯克利分校',tag:'海外',uhr:'levimyli',count:4,s:1,c:1,a:1,o:1},
  {name:'香港岭南大学',tag:'海外',uhr:'denazhu',count:3,s:2,c:0,a:0,o:1},
  {name:'南加州大学',tag:'海外',uhr:'levimyli',count:3,s:1,c:2,a:0,o:0},
  {name:'墨尔本大学',tag:'海外',uhr:'nikkyxu',count:3,s:1,c:2,a:0,o:0},
  {name:'布里斯托大学',tag:'海外',uhr:'patcoleman',count:2,s:1,c:1,a:0,o:0},
  {name:'伦敦政治经济学院',tag:'海外',uhr:'patcoleman',count:2,s:2,c:0,a:0,o:0},
  {name:'约翰霍普金斯大学',tag:'海外',uhr:'levimyli',count:2,s:1,c:0,a:0,o:1},
  {name:'纽约大学',tag:'海外',uhr:'levimyli',count:2,s:1,c:0,a:0,o:1},
  {name:'伦敦大学学院',tag:'海外',uhr:'patcoleman',count:2,s:0,c:1,a:0,o:1},
  {name:'爱丁堡大学',tag:'海外',uhr:'patcoleman',count:2,s:0,c:0,a:0,o:2},
  {name:'康奈尔大学',tag:'海外',uhr:'levimyli',count:2,s:0,c:0,a:0,o:2},
  {name:'哥伦比亚大学',tag:'海外',uhr:'levimyli',count:2,s:0,c:0,a:0,o:2},
  {name:'早稻田大学',tag:'海外',uhr:'',count:1,s:1,c:0,a:0,o:0},
  {name:'曼彻斯特大学',tag:'海外',uhr:'patcoleman',count:1,s:1,c:0,a:0,o:0},
  {name:'华威大学',tag:'海外',uhr:'patcoleman',count:1,s:1,c:0,a:0,o:0},
  {name:'斯坦福大学',tag:'海外',uhr:'levimyli',count:1,s:1,c:0,a:0,o:0},
  {name:'圣路易斯华盛顿大学',tag:'海外',uhr:'levimyli',count:1,s:0,c:1,a:0,o:0},
  {name:'宾夕法尼亚大学',tag:'海外',uhr:'levimyli',count:1,s:0,c:1,a:0,o:0},
  {name:'卡内基梅隆大学',tag:'海外',uhr:'levimyli',count:1,s:0,c:1,a:0,o:0},
  {name:'昆士兰大学',tag:'海外',uhr:'nikkyxu',count:1,s:0,c:0,a:0,o:1},
  {name:'伊利诺伊大学香槟分校',tag:'海外',uhr:'levimyli',count:1,s:0,c:0,a:0,o:1},
  {name:'格拉斯哥大学',tag:'海外',uhr:'patcoleman',count:1,s:0,c:0,a:0,o:1},
  {name:'西澳大学',tag:'海外',uhr:'nikkyxu',count:1,s:0,c:0,a:0,o:1},
  {name:'芝加哥大学',tag:'海外',uhr:'levimyli',count:1,s:0,c:0,a:0,o:1},
  {name:'新加坡管理大学',tag:'海外',uhr:'nikkyxu',count:0,s:0,c:0,a:0,o:0},
  {name:'新加坡科技与设计大学',tag:'海外',uhr:'nikkyxu',count:0,s:0,c:0,a:0,o:0},
  {name:'澳大利亚国立大学',tag:'海外',uhr:'nikkyxu',count:0,s:0,c:0,a:0,o:0},
  {name:'蒙纳士大学',tag:'海外',uhr:'nikkyxu',count:0,s:0,c:0,a:0,o:0},
  {name:'阿德莱德大学',tag:'海外',uhr:'nikkyxu',count:0,s:0,c:0,a:0,o:0},
  {name:'香港教育大学',tag:'海外',uhr:'denazhu',count:0,s:0,c:0,a:0,o:0},
  {name:'帝国理工',tag:'海外',uhr:'patcoleman',count:0,s:0,c:0,a:0,o:0},
  {name:'剑桥大学',tag:'海外',uhr:'patcoleman',count:0,s:0,c:0,a:0,o:0},
  {name:'牛津大学',tag:'海外',uhr:'patcoleman',count:0,s:0,c:0,a:0,o:0},
  {name:'杜伦大学',tag:'海外',uhr:'patcoleman',count:0,s:0,c:0,a:0,o:0},
  {name:'普林斯顿大学',tag:'海外',uhr:'levimyli',count:0,s:0,c:0,a:0,o:0},
  {name:'哈佛大学',tag:'海外',uhr:'levimyli',count:0,s:0,c:0,a:0,o:0},
  {name:'麻省理工学院',tag:'海外',uhr:'levimyli',count:0,s:0,c:0,a:0,o:0},
  {name:'耶鲁大学',tag:'海外',uhr:'levimyli',count:0,s:0,c:0,a:0,o:0},
  {name:'加州大学洛杉矶分校',tag:'海外',uhr:'levimyli',count:0,s:0,c:0,a:0,o:0},
  {name:'加州大学圣地亚哥分校',tag:'海外',uhr:'levimyli',count:0,s:0,c:0,a:0,o:0},
  {name:'波士顿大学',tag:'海外',uhr:'levimyli',count:0,s:0,c:0,a:0,o:0},
  {name:'美国西北大学',tag:'海外',uhr:'levimyli',count:0,s:0,c:0,a:0,o:0},
  {name:'杜克大学',tag:'海外',uhr:'levimyli',count:0,s:0,c:0,a:0,o:0},
  {name:'密西根大学安娜堡分校',tag:'海外',uhr:'levimyli',count:0,s:0,c:0,a:0,o:0},
  {name:'东京大学',tag:'海外',uhr:'',count:0,s:0,c:0,a:0,o:0},
  // === 非目标院校（报名≥5人，共21所）===
  {name:'华南农业大学',tag:'非目标',uhr:'-',count:13,s:7,c:4,a:0,o:2},
  {name:'上海大学',tag:'非目标',uhr:'-',count:10,s:5,c:1,a:3,o:1},
  {name:'四川农业大学',tag:'非目标',uhr:'-',count:10,s:3,c:4,a:2,o:1},
  {name:'浙江传媒学院',tag:'非目标',uhr:'-',count:10,s:2,c:0,a:1,o:7},
  {name:'成都东软学院',tag:'非目标',uhr:'-',count:9,s:2,c:2,a:4,o:1},
  {name:'深圳技术大学',tag:'非目标',uhr:'-',count:8,s:5,c:0,a:0,o:3},
  {name:'成都信息工程大学',tag:'非目标',uhr:'-',count:8,s:3,c:5,a:0,o:0},
  {name:'西安财经大学',tag:'非目标',uhr:'-',count:8,s:1,c:6,a:0,o:1},
  {name:'北师香港浸会大学',tag:'非目标',uhr:'-',count:7,s:2,c:3,a:0,o:2},
  {name:'广东技术师范大学',tag:'非目标',uhr:'-',count:6,s:2,c:1,a:1,o:2},
  {name:'华东理工大学',tag:'非目标',uhr:'-',count:6,s:0,c:4,a:0,o:2},
  {name:'广东外语外贸大学',tag:'非目标',uhr:'-',count:6,s:0,c:1,a:1,o:4},
  {name:'华中农业大学',tag:'非目标',uhr:'-',count:5,s:1,c:0,a:1,o:3},
  {name:'黑龙江东方学院',tag:'非目标',uhr:'-',count:5,s:1,c:4,a:0,o:0},
  {name:'厦门理工学院',tag:'非目标',uhr:'-',count:5,s:2,c:0,a:1,o:2},
  {name:'浙江财经大学',tag:'非目标',uhr:'-',count:5,s:1,c:1,a:1,o:2},
  {name:'汕头大学',tag:'非目标',uhr:'-',count:5,s:0,c:4,a:0,o:1},
  {name:'湖北工业大学',tag:'非目标',uhr:'-',count:5,s:0,c:0,a:3,o:2},
  {name:'深圳职业技术大学',tag:'非目标',uhr:'-',count:5,s:0,c:0,a:5,o:0},
  {name:'山西传媒学院',tag:'非目标',uhr:'-',count:5,s:0,c:0,a:5,o:0},
  {name:'广东白云学院',tag:'非目标',uhr:'-',count:5,s:0,c:0,a:0,o:5},
];

// 标签配色
const TAG_COLORS = {
  'C9': {bg:'rgba(239,68,68,0.15)',color:'#ef4444',label:'C9'},
  'T28': {bg:'rgba(245,158,11,0.15)',color:'#f59e0b',label:'T28'},
  'T60': {bg:'rgba(6,182,212,0.15)',color:'#06b6d4',label:'T60'},
  '美术院校': {bg:'rgba(34,197,94,0.15)',color:'#22c55e',label:'美术院校'},
  '垂类': {bg:'rgba(139,92,246,0.15)',color:'#8b5cf6',label:'垂类'},
  '长尾': {bg:'rgba(168,85,247,0.15)',color:'#a855f7',label:'长尾'},
  '海外': {bg:'rgba(236,72,153,0.15)',color:'#ec4899',label:'海外'},
  '非目标': {bg:'rgba(100,116,139,0.15)',color:'#94a3b8',label:'非目标'},
};
