// 开局一课2026 目标院校数据 - 从企微文档读取
// 标签: C9, T28, T60, 美术院校, 其他院校(垂类), 海外院校, 非目标院校
const SCHOOLS = [
  // === C9 ===
  {name:'上海交通大学',tag:'C9',uhr:'junoyyichen',count:8,s:3,o:2,c:2,a:1},
  {name:'浙江大学',tag:'C9',uhr:'junoyyichen',count:7,s:3,o:1,c:2,a:1},
  {name:'杭州电子科技大学',tag:'C9',uhr:'junoyyichen',count:4,s:1,o:1,c:1,a:1},
  {name:'同济大学',tag:'C9',uhr:'junoyyichen',count:7,s:2,o:2,c:2,a:1},
  {name:'复旦大学',tag:'C9',uhr:'junoyyichen',count:5,s:2,o:1,c:1,a:1},
  {name:'北京大学',tag:'C9',uhr:'erichdeng',count:5,s:1,o:3,c:1,a:0},
  {name:'清华大学',tag:'C9',uhr:'erichdeng',count:6,s:3,o:1,c:1,a:1},
  {name:'中国人民大学',tag:'C9',uhr:'erichdeng',count:4,s:1,o:2,c:1,a:0},
  {name:'天津大学',tag:'C9',uhr:'erichdeng',count:3,s:1,o:1,c:1,a:0},
  // === T28 ===
  {name:'北京航空航天大学',tag:'T28',uhr:'kvanboil',count:4,s:1,o:1,c:2,a:0},
  {name:'北京理工大学',tag:'T28',uhr:'erichdeng',count:3,s:1,o:0,c:2,a:0},
  {name:'北京邮电大学',tag:'T28',uhr:'erichdeng',count:3,s:0,o:1,c:2,a:0},
  {name:'中国科学院大学',tag:'T28',uhr:'rdeaguo',count:3,s:0,o:1,c:2,a:0},
  {name:'南开大学',tag:'T28',uhr:'erichdeng',count:0,s:0,o:0,c:0,a:0},
  {name:'山东大学',tag:'T28',uhr:'erichdeng',count:0,s:0,o:0,c:0,a:0},
  {name:'北京航空航天大学(北航)',tag:'T28',uhr:'erichdeng',count:2,s:0,o:1,c:1,a:0},
  {name:'北京交通大学',tag:'T28',uhr:'jiaweizhouu',count:1,s:1,o:0,c:0,a:0},
  {name:'北京科技大学',tag:'T28',uhr:'jiaweizhouu',count:1,s:0,o:0,c:1,a:0},
  {name:'北京交通大学',tag:'T28',uhr:'jiaweizhouu',count:1,s:1,o:0,c:0,a:0},
  // === T60 ===
  {name:'南京大学',tag:'T60',uhr:'chenruigguqi',count:2,s:0,o:1,c:1,a:0},
  {name:'东南大学',tag:'T60',uhr:'chenruigguqi',count:2,s:1,o:0,c:1,a:0},
  {name:'华东师范大学',tag:'T60',uhr:'chenruigguqi',count:1,s:0,o:0,c:1,a:0},
  {name:'华中科技大学',tag:'T60',uhr:'yichenljiang',count:5,s:1,o:1,c:2,a:1},
  {name:'武汉大学',tag:'T60',uhr:'yichenljiang',count:3,s:0,o:2,c:0,a:1},
  {name:'华中科技大学(深圳)',tag:'T60',uhr:'yichenljiang',count:1,s:0,o:0,c:1,a:0},
  {name:'中南大学',tag:'T60',uhr:'adnaluo',count:2,s:1,o:0,c:1,a:0},
  {name:'中山大学',tag:'T60',uhr:'elenapeng',count:5,s:2,o:2,c:1,a:0},
  {name:'深圳大学',tag:'T60',uhr:'elenapeng',count:2,s:0,o:1,c:1,a:0},
  {name:'中国地质大学(武汉)',tag:'T60',uhr:'yichenljiang',count:0,s:0,o:0,c:0,a:0},
  {name:'西南科技大学',tag:'T60',uhr:'adnaluo',count:0,s:0,o:0,c:0,a:0},
  {name:'湖南大学',tag:'T60',uhr:'adnaluo',count:1,s:0,o:1,c:0,a:0},
  {name:'华中科技大学(武大)',tag:'T60',uhr:'yichenljiang',count:1,s:0,o:0,c:0,a:1},
  {name:'电子科技大学',tag:'T60',uhr:'siennailu',count:3,s:1,o:1,c:1,a:0},
  {name:'西安电子科技大学',tag:'T60',uhr:'siennailu',count:1,s:0,o:0,c:1,a:0},
  {name:'四川大学',tag:'T60',uhr:'siennailu',count:2,s:0,o:1,c:0,a:1},
  {name:'重庆大学',tag:'T60',uhr:'siennailu',count:1,s:0,o:0,c:1,a:0},
  {name:'西安邮电大学',tag:'T60',uhr:'siennailu',count:0,s:0,o:0,c:0,a:0},
  {name:'重庆邮电大学',tag:'T60',uhr:'siennailu',count:0,s:0,o:0,c:0,a:0},
  {name:'西安交通大学',tag:'T60',uhr:'siennailu',count:1,s:0,o:0,c:1,a:0},
  {name:'西北工业大学',tag:'T60',uhr:'siennailu',count:1,s:0,o:1,c:0,a:0},
  {name:'西南交通大学',tag:'T60',uhr:'siennailu',count:0,s:0,o:0,c:0,a:0},
  {name:'哈尔滨工业大学(深圳)',tag:'T60',uhr:'elenapeng',count:1,s:0,o:0,c:1,a:0},
  {name:'清华大学(深圳)',tag:'T60',uhr:'elenapeng',count:1,s:0,o:0,c:1,a:0},
  {name:'北京大学(深圳)',tag:'T60',uhr:'elenapeng',count:1,s:0,o:1,c:0,a:0},
  {name:'香港中文大学(深圳)',tag:'T60',uhr:'elenapeng',count:2,s:1,o:0,c:1,a:0},
  {name:'哈尔滨工业大学',tag:'T60',uhr:'kvanboil',count:0,s:0,o:0,c:0,a:0},
  {name:'大连理工大学',tag:'T60',uhr:'kvanboil',count:0,s:0,o:0,c:0,a:0},
  {name:'东北大学',tag:'T60',uhr:'kvanboil',count:0,s:0,o:0,c:0,a:0},
  {name:'哈尔滨工程大学',tag:'T60',uhr:'kvanboil',count:0,s:0,o:0,c:0,a:0},
  {name:'武汉理工大学',tag:'T60',uhr:'adnaluo',count:0,s:0,o:0,c:0,a:0},
  {name:'南京航空航天大学',tag:'T60',uhr:'chenruigguqi',count:1,s:0,o:1,c:0,a:0},
  {name:'南方科技大学',tag:'T60',uhr:'elenapeng',count:1,s:0,o:0,c:1,a:0},
  {name:'广东工业大学',tag:'T60',uhr:'elenapeng',count:1,s:0,o:0,c:0,a:1},
  // === 美术院校 ===
  {name:'中国美术学院',tag:'美术院校',uhr:'rdeaguo',count:2,s:0,o:0,c:0,a:2},
  {name:'中央美术学院',tag:'美术院校',uhr:'rdeaguo',count:1,s:0,o:0,c:0,a:1},
  {name:'中国传媒大学',tag:'美术院校',uhr:'erichdeng',count:2,s:1,o:0,c:0,a:1},
  {name:'四川美术学院',tag:'美术院校',uhr:'siennailu',count:1,s:0,o:0,c:0,a:1},
  {name:'广州美术学院',tag:'美术院校',uhr:'siennailu',count:1,s:0,o:0,c:0,a:1},
  {name:'西安美术学院',tag:'美术院校',uhr:'siennailu',count:0,s:0,o:0,c:0,a:0},
  {name:'清华大学美术学院',tag:'美术院校',uhr:'erichdeng',count:1,s:0,o:0,c:0,a:1},
  {name:'四川音乐学院',tag:'美术院校',uhr:'siennailu',count:0,s:0,o:0,c:0,a:0},
  {name:'鲁迅美术学院',tag:'美术院校',uhr:'kvanboil',count:0,s:0,o:0,c:0,a:0},
  {name:'天津美术学院',tag:'美术院校',uhr:'kvanboil',count:0,s:0,o:0,c:0,a:0},
  {name:'湖北美术学院',tag:'美术院校',uhr:'yichenljiang',count:0,s:0,o:0,c:0,a:0},
  {name:'吉林动画学院',tag:'美术院校',uhr:'rdeaguo',count:1,s:0,o:0,c:0,a:1},
  {name:'江南大学',tag:'美术院校',uhr:'chenruigguqi',count:1,s:0,o:0,c:0,a:1},
  {name:'南京艺术学院',tag:'美术院校',uhr:'chenruigguqi',count:0,s:0,o:0,c:0,a:0},
  {name:'北京电影学院',tag:'美术院校',uhr:'kvanboil',count:1,s:0,o:0,c:0,a:1},
  // === 其他院校(垂类) ===
  {name:'江西财经大学',tag:'垂类',uhr:'rdeaguo',count:0,s:0,o:0,c:0,a:0},
  {name:'四川大学锦江学院',tag:'垂类',uhr:'rdeaguo',count:0,s:0,o:0,c:0,a:0},
  {name:'电子科大成都学院',tag:'垂类',uhr:'rdeaguo',count:0,s:0,o:0,c:0,a:0},
  {name:'北京师范大学',tag:'垂类',uhr:'erichdeng',count:1,s:0,o:1,c:0,a:0},
  {name:'陕西师范大学',tag:'垂类',uhr:'siennailu',count:0,s:0,o:0,c:0,a:0},
  {name:'西北大学',tag:'垂类',uhr:'siennailu',count:0,s:0,o:0,c:0,a:0},
  {name:'中国政法大学',tag:'垂类',uhr:'erichdeng',count:0,s:0,o:0,c:0,a:0},
  {name:'对外经济贸易大学',tag:'垂类',uhr:'erichdeng',count:0,s:0,o:0,c:0,a:0},
  {name:'中央财经大学',tag:'垂类',uhr:'erichdeng',count:0,s:0,o:0,c:0,a:0},
  {name:'上海财经大学',tag:'垂类',uhr:'chenruigguqi',count:1,s:0,o:1,c:0,a:0},
  {name:'北京师范大学(珠海)',tag:'垂类',uhr:'elenapeng',count:0,s:0,o:0,c:0,a:0},
  {name:'电子科技大学(深圳)',tag:'垂类',uhr:'elenapeng',count:1,s:0,o:0,c:1,a:0},
  {name:'吉林大学',tag:'垂类',uhr:'kvanboil',count:0,s:0,o:0,c:0,a:0},
  // === 海外院校 ===
  {name:'新加坡国立大学',tag:'海外',uhr:'rdeaguo',count:2,s:1,o:1,c:0,a:0},
  {name:'南洋理工大学',tag:'海外',uhr:'rdeaguo',count:1,s:0,o:0,c:1,a:0},
  {name:'新加坡管理大学',tag:'海外',uhr:'rdeaguo',count:0,s:0,o:0,c:0,a:0},
  {name:'新加坡科技与设计大学',tag:'海外',uhr:'rdeaguo',count:0,s:0,o:0,c:0,a:0},
  {name:'澳大利亚国立大学',tag:'海外',uhr:'rdeaguo',count:0,s:0,o:0,c:0,a:0},
  {name:'悉尼大学',tag:'海外',uhr:'rdeaguo',count:1,s:0,o:1,c:0,a:0},
  {name:'墨尔本大学',tag:'海外',uhr:'rdeaguo',count:1,s:0,o:0,c:1,a:0},
  {name:'莫纳什大学',tag:'海外',uhr:'rdeaguo',count:0,s:0,o:0,c:0,a:0},
  {name:'新南威尔士大学',tag:'海外',uhr:'rdeaguo',count:0,s:0,o:0,c:0,a:0},
  {name:'西澳大学',tag:'海外',uhr:'rdeaguo',count:0,s:0,o:0,c:0,a:0},
  {name:'昆士兰大学',tag:'海外',uhr:'rdeaguo',count:0,s:0,o:0,c:0,a:0},
  {name:'阿德莱德大学',tag:'海外',uhr:'rdeaguo',count:0,s:0,o:0,c:0,a:0},
  {name:'香港大学',tag:'海外',uhr:'denazhu',count:2,s:1,o:0,c:1,a:0},
  {name:'香港中文大学',tag:'海外',uhr:'denazhu',count:1,s:0,o:1,c:0,a:0},
  {name:'香港科技大学',tag:'海外',uhr:'denazhu',count:3,s:1,o:1,c:1,a:0},
  {name:'香港理工大学',tag:'海外',uhr:'denazhu',count:1,s:0,o:0,c:1,a:0},
  {name:'香港城市大学',tag:'海外',uhr:'denazhu',count:1,s:0,o:1,c:0,a:0},
  {name:'香港浸会大学',tag:'海外',uhr:'denazhu',count:0,s:0,o:0,c:0,a:0},
  {name:'香港岭南大学',tag:'海外',uhr:'denazhu',count:0,s:0,o:0,c:0,a:0},
  {name:'香港教育大学',tag:'海外',uhr:'denazhu',count:0,s:0,o:0,c:0,a:0},
  {name:'帝国理工',tag:'海外',uhr:'patcoleman',count:1,s:0,o:0,c:1,a:0},
  {name:'伦敦大学学院',tag:'海外',uhr:'patcoleman',count:1,s:0,o:1,c:0,a:0},
  {name:'伦敦政治经济学院',tag:'海外',uhr:'patcoleman',count:0,s:0,o:0,c:0,a:0},
  {name:'剑桥大学',tag:'海外',uhr:'patcoleman',count:0,s:0,o:0,c:0,a:0},
  {name:'牛津大学',tag:'海外',uhr:'patcoleman',count:0,s:0,o:0,c:0,a:0},
  {name:'爱丁堡大学',tag:'海外',uhr:'patcoleman',count:0,s:0,o:0,c:0,a:0},
  {name:'曼彻斯特大学',tag:'海外',uhr:'patcoleman',count:0,s:0,o:0,c:0,a:0},
  {name:'华威大学',tag:'海外',uhr:'patcoleman',count:1,s:0,o:0,c:1,a:0},
  {name:'杜伦大学',tag:'海外',uhr:'patcoleman',count:0,s:0,o:0,c:0,a:0},
  {name:'布里斯托大学',tag:'海外',uhr:'patcoleman',count:0,s:0,o:0,c:0,a:0},
  {name:'格拉斯哥大学',tag:'海外',uhr:'patcoleman',count:0,s:0,o:0,c:0,a:0},
  {name:'普林斯顿大学',tag:'海外',uhr:'levinyij',count:0,s:0,o:0,c:0,a:0},
  {name:'哈佛大学',tag:'海外',uhr:'levinyij',count:0,s:0,o:0,c:0,a:0},
  {name:'麻省理工学院',tag:'海外',uhr:'levinyij',count:0,s:0,o:0,c:0,a:0},
  {name:'斯坦福大学',tag:'海外',uhr:'levinyij',count:0,s:0,o:0,c:0,a:0},
  {name:'耶鲁大学',tag:'海外',uhr:'levinyij',count:0,s:0,o:0,c:0,a:0},
  {name:'加州大学伯克利分校',tag:'海外',uhr:'levinyij',count:0,s:0,o:0,c:0,a:0},
  {name:'南加州大学',tag:'海外',uhr:'levinyij',count:1,s:0,o:0,c:1,a:0},
  {name:'杜克大学',tag:'海外',uhr:'levinyij',count:0,s:0,o:0,c:0,a:0},
  // === 非目标院校 ===
  {name:'非目标院校(其他)',tag:'非目标',uhr:'-',count:0,s:0,o:0,c:0,a:0},
];

// 标签配色
const TAG_COLORS = {
  'C9': {bg:'rgba(239,68,68,0.15)',color:'#ef4444',label:'C9'},
  'T28': {bg:'rgba(245,158,11,0.15)',color:'#f59e0b',label:'T28'},
  'T60': {bg:'rgba(6,182,212,0.15)',color:'#06b6d4',label:'T60'},
  '美术院校': {bg:'rgba(34,197,94,0.15)',color:'#22c55e',label:'美术院校'},
  '垂类': {bg:'rgba(139,92,246,0.15)',color:'#8b5cf6',label:'垂类'},
  '海外': {bg:'rgba(236,72,153,0.15)',color:'#ec4899',label:'海外'},
  '非目标': {bg:'rgba(100,116,139,0.15)',color:'#94a3b8',label:'非目标'},
};
